### ISSUE TITLE
kubeasz/docs/quickStart.md 小错误

### ISSUE THREAD

**Issue by sshling** [gjmzj/kubeasz#2]
`kubectl clusterinfo # 可以看到kubernetes master(apiserver)组件 running`

应该为 ` kubectl cluster-info `
我在centos7 测试机器上是这样，

我也是第一次学习k8s, 在我机器上好几个命令报如下的错误，请教下是哪里配错了？
```
[root@mnode ~]# kubectl cluster-info
Kubernetes master is running at https://192.168.21.3:6443
[root@mnode ~]# kubectl get node 
The connection to the server 192.168.21.3:6443 was refused - did you specify the right host or port?
```
查看集群信息，地址、端口没有错呢
先谢谢

**Comment by gjmzj** [comment]
1.感谢指出kubectl cluster-info
2.感觉是kubeconfig配置有点问题，检查下里面的证书等信息，
`vi ~/.kube/config`
你是allinone集群，还是多节点集群？

**Comment by sshling** [comment]
allinone集群
```
# cat .kube/config 
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUR0akNDQXA2Z0F3SUJBZ0lVSThOa1ZCTmNiTXR2MzdLWlk2MFRnNENSdEVJd0RRWUpLb1pJaHZjTkFRRUwKQlFBd1lURUxNQWtHQTFVRUJoTUNRMDR4RVRBUEJnTlZCQWdUQ0VoaGJtZGFhRzkxTVFzd0NRWURWUVFIRXdKWQpVekVNTUFvR0ExVUVDaE1EYXpoek1ROHdEUVlEVlFRTEV3WlRlWE4wWlcweEV6QVJCZ05WQkFNVENtdDFZbVZ5CmJtVjBaWE13SGhjTk1UY3hNakF5TVRFeU9UQXdXaGNOTWpJeE1qQXhNVEV5T1RBd1dqQmhNUXN3Q1FZRFZRUUcKRXdKRFRqRVJNQThHQTFVRUNCTUlTR0Z1WjFwb2IzVXhDekFKQmdOVkJBY1RBbGhUTVF3d0NnWURWUVFLRXdOcgpPSE14RHpBTkJnTlZCQXNUQmxONWMzUmxiVEVUTUJFR0ExVUVBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKCktvWklodmNOQVFFQkJRQURnZ0VQQURDQ0FRb0NnZ0VCQU5vYjgyY3UrdERqMHBqZXp4dTJJSEY4WG0rblM3eG4KVWYwNHd6M2Yrai9ZMVlHSlFWSThpUkV4bEtMU3V0Wk9uaFg1NC9pQlBybjE1M0Y1YWIwL3hLRHJCQUVMQURGQwpZVm1CcnhwU3BzeEV2czcveTJ5aWFHK2h5bGV5RDRyaVZkMXB2TmxQRjY2RzJPSWtLV2o5RnQ5M1Y1YS9FTkJHCk5Nd1FMNUYxZENTMGI0R2dvTndKK1RiRHRFVWpnci9SQXdCNDE0THozRmp4TExHVzVFZGJMdzBnTk9uRDZrWGsKdHFER1EyVGkyMnc0d21WbEJtckdsSGQ1anRMR2RMTmduckJwS1pOWEtHVVdwU2Z6bk9WL1U3UCsvSUV5aE0zWQpBdHhTRkV5MkNNWWsyZ0VrVGFUdHFhMWVWYUNJUzJxc2xiQjQrM29lV2piZXYweURWMjRxdlZVQ0F3RUFBYU5tCk1HUXdEZ1lEVlIwUEFRSC9CQVFEQWdFR01CSUdBMVVkRXdFQi93UUlNQVlCQWY4Q0FRSXdIUVlEVlIwT0JCWUUKRkh4T1B1VU9RTllVWUpkOHJEV1VzU2pzcll0K01COEdBMVVkSXdRWU1CYUFGSHhPUHVVT1FOWVVZSmQ4ckRXVQpzU2pzcll0K01BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQ3MrWVlFM1VaQVREMGg2VjFJTWF2OUMrT0grZENrCm5BbmVqcHMwdzEvNkc2ZGxiQXJzWEhLVmhLTzc0K0pKUmQ2VGJ2dkNKSGRaeDQwTzNqTWMzN1RsUE1MVlRQdjAKS082TTZqQTdOd3RMWDQwRkVYcHFiMG0zZ3AwL3psTThUdS9vYnFhV1l2emlEK29ZTytOMy9URTg1NUFmS2RwUwpDdm0vVUUyU080aXRXVjU3SjRsOVE4ZGx5WW4rTy9JQlduMVh3ckxnZ1lUOWxnamFvVE9hQ2ZMWGJRQXEvVlMwCkxlUWVwOFJaaC9YREYrV2VZdnJveVhERjd6dDlVNXBMOG1EQWwzVUMrVU9Oa3FTcGlFeUhlWEtwemVHTjNVM0UKakM4RzQvN3hiSEZUK1FEVFZyNzBZbEsyNlB2czFjVjRTN2k1Sm05M0hwSXFVKzFyL2VwdHEwZEcKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    server: https://192.168.21.3:6443
  name: kubernetes
contexts:
- context:
    cluster: kubernetes
    user: admin
  name: kubernetes
current-context: kubernetes
kind: Config
preferences: {}
users:
- name: admin
  user:
    as-user-extra: {}
    client-certificate-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUQxVENDQXIyZ0F3SUJBZ0lVU3hxVHJwWXowSS9sZjBiRGJmbFVzbjJ2dDFjd0RRWUpLb1pJaHZjTkFRRUwKQlFBd1lURUxNQWtHQTFVRUJoTUNRMDR4RVRBUEJnTlZCQWdUQ0VoaGJtZGFhRzkxTVFzd0NRWURWUVFIRXdKWQpVekVNTUFvR0ExVUVDaE1EYXpoek1ROHdEUVlEVlFRTEV3WlRlWE4wWlcweEV6QVJCZ05WQkFNVENtdDFZbVZ5CmJtVjBaWE13SGhjTk1UY3hNakF5TVRFeU9UQXdXaGNOTWpjeE1UTXdNVEV5T1RBd1dqQm5NUXN3Q1FZRFZRUUcKRXdKRFRqRVJNQThHQTFVRUNCTUlTR0Z1WjFwb2IzVXhDekFKQmdOVkJBY1RBbGhUTVJjd0ZRWURWUVFLRXc1egplWE4wWlcwNmJXRnpkR1Z5Y3pFUE1BMEdBMVVFQ3hNR1UzbHpkR1Z0TVE0d0RBWURWUVFERXdWaFpHMXBiakNDCkFTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTnRqZ0xyZVoxeFhiRlhuYUNkQ0xtV0oKNzNCa25helFockpYSG9jK0thSTUzZXk2d3kybHpKdnhmNkRzd1cwbit4SFhDdGdsRkMxMkFxZzBZOE9nN1hzaApkc2d6V0ZTMXRUcFlGY3AyMHNEd0d5UEw4V2tYcjlPZWxTa2hocSs0aWNtclgrSGxkaUJtaW1CYWNZUGpzV1ZiCjduWGEvUm5Wd2MyVVJUdzJJQ1RYNWNZZFNUOVpHQ2xra1dPUVlNcGZoWjhWTE1kZ0dlSEdQeXNDN0IzMVZVZEQKTkFqVmcyVE9rYTliTGhpdjBuc1A2d3F2OExiSUxMcE1FUFQ3bGRmdmZlaXJlQkNnOXFkeTRVTm9WOUpHN3RuMAorZ0hPUmNLQXlmcU5oeTNXbjZMd2h2RTRHazRTMEpZMkF2WmVtVUk5TWdCNXpJdXRhMHhPVHFLOFUwbzlBc0VDCkF3RUFBYU4vTUgwd0RnWURWUjBQQVFIL0JBUURBZ1dnTUIwR0ExVWRKUVFXTUJRR0NDc0dBUVVGQndNQkJnZ3IKQmdFRkJRY0RBakFNQmdOVkhSTUJBZjhFQWpBQU1CMEdBMVVkRGdRV0JCVDJKQ2IvNW9xcUhiOURXV2VTR0lPaApjVFp1U3pBZkJnTlZIU01FR0RBV2dCUjhUajdsRGtEV0ZHQ1hmS3cxbExFbzdLMkxmakFOQmdrcWhraUc5dzBCCkFRc0ZBQU9DQVFFQVpLNUpGOXR2aWVPalV2bXhGUENwRFYxakNMdEEvTEMxLzh2ZGFhc1dLQytHMFFIcTI0dTYKeXJobk0yR3djZlFMNThkVGtYMk1vMDZSSU1rY1F0U2ZoMXh5c2ZHUWhORVNUZ1k0aHBXV1MxSG1DZkVpMERySgpwamgxdlkvZDVwOE0zN25zWGpSRHlCSmZ5bzhUYis1WU1MbHhuejJaTjkybUdKeW9BR2RGdGtFYlhMK3NHVWdHCk9VUlVPTm4ybHNRY2lOVUZMYkErSFN2TkVCTXd3ZCtFVll3YS9tVkJPcGppckZ6L2lLbkVYOFVnRHZYR25wMHQKUGVmcWEzcWllaGNTTUlGbldQRWdiUHBDdEhtcEtBYmQ4azFaQXp1dWhuQjdhZkdlYWJlaC9aWmUrUm9OajVqbgpUc0laZ2ZQelFZSU5DaXoyQW12b2grdHQ1eEtXUUpyZFNnPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    client-key-data: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFb3dJQkFBS0NBUUVBMjJPQXV0NW5YRmRzVmVkb0owSXVaWW52Y0dTZHJOQ0dzbGNlaHo0cG9qbmQ3THJECkxhWE1tL0Yvb096QmJTZjdFZGNLMkNVVUxYWUNxRFJqdzZEdGV5RjJ5RE5ZVkxXMU9sZ1Z5bmJTd1BBYkk4dngKYVJldjA1NlZLU0dHcjdpSnlhdGY0ZVYySUdhS1lGcHhnK094WlZ2dWRkcjlHZFhCelpSRlBEWWdKTmZseGgxSgpQMWtZS1dTUlk1Qmd5bCtGbnhVc3gyQVo0Y1kvS3dMc0hmVlZSME0wQ05XRFpNNlJyMXN1R0svU2V3L3JDcS93CnRzZ3N1a3dROVB1VjErOTk2S3Q0RUtEMnAzTGhRMmhYMGtidTJmVDZBYzVGd29ESitvMkhMZGFmb3ZDRzhUZ2EKVGhMUWxqWUM5bDZaUWoweUFIbk1pNjFyVEU1T29yeFRTajBDd1FJREFRQUJBb0lCQVFDdmZFb09MN1F4MHVRZgpXcmlmSG5zS1VXa3JWL0FmdWJUa2xuY2U2d1JXZFQ4bENzYndqbnk2Q0ZSMG5xeWg2YWNVd0JRMmpJSTFVdjRSCkdjYnJScUJ2SzNkZDhHUXBiaWVHZ2NyOFprdHlkUnpnWjFPMUluTk1MTDlYWlMvZEF4bUVMUWJISk1wMlpFOHYKZjJqcGZJbjdiNnV3cmZoaVgrOWp4OFFSdzZHMmxWZnpVRS85NEV3emZvSHFNNS80Q1Fackp3N1RPSTFtZ2NaYQo3MGVUWlJJRU1kSW9kcXl2M1BtQVVzeCtPQmVYK2pMU3VZeGM4NGpsOXVlSzlEcGYrSUg4QnB4akdGcnh3Q0MwCk8xWGllTGxwcmFXQlNDS29Hb0cwNFF1VTE5MXhjc3VKMlloOGVlSkZrdkNhTi9zRHlwVlRVYnBZRVB2QmJweDQKY2E5RW1pZ2hBb0dCQVBoaWVMMEgySXI3bDdOMitZMjFBQjU2bVN5NFV5dFJsQnpVQ0h1QTBUQXhJT1lEdkUyOQpXYVFERktvcE5wV21YS21tamwvZS9OZU5FbC9NSGZ3b3FMcUd6Kyt5Y0kxL2dHb3ZSSUhmdDUxMmpUYk5UNjVxCjR2TUVSMWRpVGJ1SG9FdFZYVEdkMHNFOW9EM3dORVp1cDl4UGZSTHBSMnMvVExtS2RBbXVTK3ZkQW9HQkFPSWQKY21OcmFXblFZdUVrejBRK2pnY2ZrdjNab08remFOV1VDdXlGNlpEZ29idFBYeUtKcGx5YjFoZ3VuNXBXdDlVSwo0U05ZQ0xmbklSeDFtdTlQWHZtOS90a0dQQS8rV3I1NUQ2TWhuUjU5dGsvVmdPTCsxSEFESDZ4dzBCSWNzdnNuCmFMUDUvUXV2cENWSDZjY2tPd1BMNDgwNlRtSjlRVm5WZnVCSUZnWTFBb0dBWXR5bTIrNVVoVFVRczNER2NWMjYKbDJjS3NwOEhFM1hiOHdGK0F0Sko4Tm1ORTZBbkFmWTh5S2dsUUhrNDdhV1N1ais5NlhEU3lHU3hESW9zNFNHNQp6c3c3MVZiN3I0WXhNWkp3dlJTemU2d2xGc3Z2VENmay92OFQramI1WTR2ZkJEME00K1BDY0FHOFZ3clZjN2MxCmZ0M3dsV2RlY3RSMkVGK0lRaFlxeDgwQ2dZQWtsUlVMcHJZZ1MzbWo2VnVyTTkrd29WZ2J2OWo4enU3NEZ3S0oKYjhUeERwYThBa1JuQnhRbVNZUWkxM0EwL1RDeXhCYldyQWlGRUZ6WUNPTHZNczB2NUtCVnBsK1RTdGlObG5LRQpOd3ovZ09FOUcxTEY1dXFoMEsrUUs1Uk9TZHhmSytvUnJERlhjYXhCNTllWHczSFUxR2pmckQ1QVN2bUd1amJUCnZIWHJ2UUtCZ0Z6TVNlb0VRM2F3U09uV04zbDBxS241NDBRdzgwSFBuWk0xbEl2Vi9WcXBleXZITzRFSGJHM3AKc1hmeDVkWTBEa0ZsV01yT2g4SU1kWFBtSXJiUTUyZis1RkJkMzkyWjFxd3RkdVhYKzMzdjVaSVJjNjdkYVlkagpVYllVSjcvRFMxOG1jU0ZJcXRSQ1ZmdHpubUU2cCtXTTlvM3JJK2MvYXhSbVdCNExkTXZJCi0tLS0tRU5EIFJTQSBQUklWQVRFIEtFWS0tLS0tCg==
```
