### ISSUE TITLE
当ingress配置了https后，dashboard启用traefik-ingress时，不能正常访问的问题解决

### ISSUE THREAD

**Issue by lichengx** [gjmzj/kubeasz#403]
kubernetes-dashboard配置文件
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name:  kubernetes-dashboard
  namespace: kube-system
  annotations:
    traefik.ingress.kubernetes.io/redirect-entry-point: https
spec:
  rules:
  - host: dashboard.xxxxxxxx.com
    http:
      paths:
      - path: /
        backend:
          serviceName: kubernetes-dashboard
          servicePort: 443
```
需要traefik-conf的配置文件添加
```
insecureSkipVerify = true
```
才能正常访问。
完整的traefik-conf配置如下
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik-conf
  namespace: kube-system
data:
  traefik.toml: |
    insecureSkipVerify = true
    defaultEntryPoints = ["http", "https"]
    [entryPoints]
      [entryPoints.http]
        address = ":80"
        # 配置http 强制跳转 https
        #[entryPoints.http.redirect]
        #  entryPoint = "https"
      [entryPoints.https]
        address = ":443"
        [entryPoints.https.tls]
          [[entryPoints.https.tls.certificates]]
            CertFile = "/ssl/tls.crt"
            KeyFile = "/ssl/tls.key"
```
如果是只更新traefik-conf，还需要把traefik-ingress-controller重启一下。
希望对大家有所帮助，希望把
```
insecureSkipVerify = true
```
配置项添加进去
