### ISSUE TITLE
kubernetes master 地址访问提示:forbidden: User \"admin\" cannot get path 

### ISSUE THREAD

**Issue by liuyjishg** [gjmzj/kubeasz#434]
请教一下大神，集群安装使用没有问题，今天想访问一下kubernetes master地址 提示：禁止用户admin访问/ ，这是为何。

集群地址
[root@master02 ~]# kubectl cluster-info
Kubernetes master is running at https://10.88.0.10:8443
To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.

访问报错
[root@master02 ~]# curl -u admin:admin https://10.88.0.10:8443 --insecure
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {
    
  },
  "status": "Failure",
  "message": "forbidden: User \"admin\" cannot get path \"/\"",
  "reason": "Forbidden",
  "details": {
    
  },
  "code": 403

**Comment by gjmzj** [comment]
因为我项目中admin 用户并没授权 / 访问，具体可以查看 `manifests/dashboard/ui-admin-rbac.yaml` 配置；
如果你需要这个权限的话，可以执行如下：
```
cat > admin-user-binding.yaml << EOF
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ui-admin-binding
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ui-admin
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: admin
EOF 
kubectl apply -f admin-user-binding.yaml
```
